-- Security Audit Log table
CREATE TABLE IF NOT EXISTS `security_audit_log` (
    `id` INT(11) AUTO_INCREMENT PRIMARY KEY,
    `event_type` VARCHAR(50) NOT NULL,
    `user_id` INT(11) DEFAULT NULL,
    `username` VARCHAR(100) DEFAULT NULL,
    `target_user_id` INT(11) DEFAULT NULL,
    `success` TINYINT(1) DEFAULT NULL,
    `ip_address` VARCHAR(45) DEFAULT NULL,
    `user_agent` VARCHAR(500) DEFAULT NULL,
    `config_key` VARCHAR(100) DEFAULT NULL,
    `old_value` TEXT DEFAULT NULL,
    `new_value` TEXT DEFAULT NULL,
    `export_type` VARCHAR(50) DEFAULT NULL,
    `module` VARCHAR(50) DEFAULT NULL,
    `record_count` INT(11) DEFAULT NULL,
    `format` VARCHAR(20) DEFAULT NULL,
    `data_type` VARCHAR(50) DEFAULT NULL,
    `action` VARCHAR(100) DEFAULT NULL,
    `details` TEXT DEFAULT NULL,
    `old_role` VARCHAR(50) DEFAULT NULL,
    `new_role` VARCHAR(50) DEFAULT NULL,
    `api_key_id` VARCHAR(100) DEFAULT NULL,
    `endpoint` VARCHAR(500) DEFAULT NULL,
    `http_method` VARCHAR(10) DEFAULT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX `idx_event_type` (`event_type`),
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
